:compat-mode:
= Lab 03b - Leveraging Spring Cloud Connectors for Service Binding

In this lab we'll bind our RESTful web service from link:../lab_03a/lab_03a_rest.adoc[Lab 03a] to a MySQL database and leverage Spring Cloud Connectors to easily connect to it.

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_03/lab_03b/complete/companies`.

== Using Spring Cloud Connectors

. Change to the lab directory (the initial state for this lab is the same as the completed state for link:../lab_03a/lab_03a_rest.adoc[Lab 03a], so you can choose to continue with that project if you like):
+
----
$ cd $COURSE_HOME/day_01/session_03/lab_03b/initial/companies
----

. At present we're still using the in-memory database. Let's connect to a MySQL database service.
From the CLI, let's _create_ a MySQL service instance:
+
[source,bash]
----
$ cf cs p-mysql 100mb-dev companies-db
Creating service companies-db...
OK
----
+
Again, if `p-mysql` service is not available, please use the free `spark` plan from `cleardb` like this `cf cs cleardb spark companies-db`.

. Next add the service to your application manifest, which will _bind_ the service to our application on the next push. We'll also add an environment variable to switch on the ``cloud'' profile,
+
[source,yml]
----
---
applications:
- name: companies
  memory: 512M
  instances: 1
  path: target/lab_03b-companies-1.0.0.jar
  timeout: 180
  services:                        # Add
  - companies-db                      # these
  env:                             # four
    SPRING_PROFILES_ACTIVE: cloud  # lines
----
+
You can also accomplish the service binding by explicitly binding the service at the command-line:
+
[source,bash]
----
$ cf bind-service companies companies-db
Binding service companies-db to app companies...
OK
----

. Next we'll add Spring Cloud and MySQL dependencies to our maven pom file. Just after the dependency declaration for +h2+, add add the following in the +dependencies+ section:
+
[source,xml]
----

	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-spring-service-connector</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-cloudfoundry-connector</artifactId>
	</dependency>
	<dependency>
		<groupId>org.mariadb.jdbc</groupId>
		<artifactId>mariadb-java-client</artifactId>
	</dependency>


----
+

. Next, let's create the package +io.pivotal.demo.config+ and create in that package the class +CloudDataSourceConfig+. Add the following code:
+
[source,java]
----
@Profile("cloud")
@Configuration
public class CloudDataSourceConfig extends AbstractCloudConfig {
    @Bean
    public DataSource dataSource() {
        return connectionFactory().dataSource();
    }
}
----
+
The +@Profile+ annotation will cause this class (which becomes Spring configuration when annotated as +@Configuration+) to be added to the configuration set because of the +SPRING_PROFILES_ACTIVE+ environment variable we added earlier. You can still run the application locally (with the default profile) using the embedded database.
+
With this code, Spring Cloud will detect a bound service that is compatible with +DataSource+, read the credentials, and then create a +DataSource+ as appropriate (it will throw an exception otherwise).

. Add the following to +src/main/resources/application.yml+ to cause Hibernate to create the database schema and import data at startup. This is done automatically for embedded databases, but not for a custom ++DataSource++. Other Hibernate native properties can be set in a similar fashion:
+
[source,yml]
----
spring.jpa:
  hibernate.ddl-auto: create
  database-platform: org.hibernate.dialect.MySQLDialect
----

. Build the application:
+
[source,bash]
----
$ mvn clean package
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----

. In your web browser, have a look at the env variables used by your application 
(\http://companies-<your_path>.cfapps.io/env)
+
[source,bash]
----
...
"vcap" : {
    "vcap.services.companies-db.name" : "companies-db",
    "vcap.application.limits.mem" : "1024",
    "vcap.services.companies-db.label" : "p-mysql",
    ...
    "vcap.services.companies-db.tags" : "mysql,relational",
    ...
----
The application is now running against a MySQL database.

== Customising the +DataSource+

. You can customize the database connection that Spring Cloud creates with a few lines of code. Change the +dataSource+ method in +CloudDataSourceConfig+ to add some pooling and connection configuration:
+
[source,java]
----
@Bean
public DataSource dataSource() {
    PooledServiceConnectorConfig.PoolConfig poolConfig =
            new PooledServiceConnectorConfig.PoolConfig(5, 200);

    DataSourceConfig.ConnectionConfig connectionConfig =
            new DataSourceConfig.ConnectionConfig("characterEncoding=UTF-8");
    DataSourceConfig serviceConfig = new DataSourceConfig(poolConfig, connectionConfig);

    return connectionFactory().dataSource("companies-db", serviceConfig);
}
----

. Build the application:
+
[source,bash]
----
$ mvn clean package
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----
