= Lab 1c - Externalizing Configuration with Spring Boot

Estimated time to complete: 20 minutes

== Refactoring to Externalize the Config

. You should work using the same project as in the previous labs

. Inside the folder `src/main/resources/`, you will see a file called `application.properties`. Rename that file into `application.yml`

NOTE: Spring Boot allows to work with properties files or YML files indifferently. In this workshop you will be using YML files because their syntax is more powerful (and still fairly simple!)

. Inside `application.yml` paste the following:
+
----
greeting: Hello
----

. To the class `io.pivotal.spring.hello.HelloSpringBootApplication`, add a `greeting` field and inject its value:
+
----
@Value("${greeting}")
String greeting = "Bonjour";
----

. Also `io.pivotal.spring.hello.HelloSpringBootApplication`, change the return statement of `hello()` to the following:
+
----
return String.format("%s World!", greeting);
----

. Make sure your application is running and visit http://localhost:8080 in your browser. Which of the values is picked up? Is it the local one ("Bonjour") or the one in `application.yml` ("Hello")?


== Using Environment Variables for Config

. You should now stop the application inside your IDE because you are going to launch it from the command line

. You are now going to add an environment variable from the command line. You should compile and run the application as shown below:
+
----
Windows:
> mvn clean package
> set GREETING=Ohai && java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar

Linux, MacOS:
$ mvn clean package
$ GREETING=Ohai java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

NOTE: in case of any issue running your application, you should confirm that your jar file is the same as in the above code (it varies depending on the name of our project)


. Visit the application in the browser (http://localhost:8080), and verify that the output has changed to the following:
+
----
Ohai World!
----

. Stop the application.

. Visit http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html to learn more about this outcome and the entire priority scheme for conflict resolution.
