= Lab 1a - Getting Started with Spring Boot

Estimated time to complete: 20 minutes

== Generate a project from start.spring.io

. In your browser, visit https://start.spring.io.

. Fill out the *Project metadata* fields as follows:
+
Group:: `io.spring.pivotal`
Artifact:: `hello-spring-boot`
Search For Dependencies:: `Web`
Spring Boot version:: `1.3.3`

. Click the *Generate Project* button. Your browser will download a zip file.
Unpack that zip file at `$COURSE_HOME/day_01/session_01/lab_01a/initial`.

== Run it locally

. Import the project's `pom.xml` into your editor/IDE of choice.

. Add a `@RestController` annotation to the class `io.pivotal.spring.hello.HelloSpringBootApplication`
to indicate that we wish to return REST (data) responses not HTML.
+
It will be marked in red, so you need to add the import for this annotation.

NOTE: In Eclipse/STS press CTRL-SHIFT-O (MacOS: COMMAND-SHIFT-O). In IntelliJ use CTRL+ALT+o (MacOS: COMMAND-ALT-o)

. Add the following request handler method to the class `io.pivotal.spring.hello.HelloSpringBootApplication` after the static `main` method:
+
[source,java]
----
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
----
+
Again you will need to use the IDE to import the `@RequestMapping` annotation.

. To run the application:
  * Eclipse/STS: Right click in the editor window and select `Run As` -> `Spring Boot App`.
  * IntelliJ: In the editor window press CTRL-SHIFT-R (MacOS: COMMAND-SHIFT-R)
+
Wait for the application to start up.

. Open http://localhost:8080 in your browser and it should return `Hello World!`.

*Congratulations!*
You've just completed your first Spring Boot application.
