:compat-mode:
= Lab 03a - Build a Hypermedia-Driven RESTful Web Service with Spring Data REST

Estimated time to complete: 30 minutes

In this lab we'll utilize Spring Boot, Spring Data, and Spring Data REST to create a fully-functional hypermedia-driven RESTful web service. We'll then deploy it to Pivotal Cloud Foundry.


== Initializing the Application

. Import the project `$COURSE_HOME/day_01/session_03/lab_03a/initial/companies` into your IDE.

. Open its `pom.xml` file and add a runtime dependency on the H2 in-memory database:
+
[source,java]
----
	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
		<scope>runtime</scope>
	</dependency>
----

. Create the package +io.pivotal.demo.domain+ and in that package create the class +Company+. Into that file you can paste the following source code, which represents companies based on exchange and trading symbol:

NOTE: JPA (Java Persistence API) is an abstraction layer on top of Hibernate. When importing annotations such as `@Entity`, you should use the package `javax.persistence` instead of `org.hibernate`.


[source,java]
----
@Entity
@Table(name = "COMPANIES")
public class Company implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String name;

    private String symbol;

    private String exchange;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getExchange() {
        return exchange;
    }

    public void setExchange(String exchange) {
        this.exchange = exchange;
    }
}
----


. Create the package +io.pivotal.demo.repositories+ and in that package create the interface +CompanyRepository+. Paste the following code and add appropriate imports:
+
[source,java]
----
@RepositoryRestResource(collectionResourceRel = "companies", path = "companies")
public interface CompanyRepository extends PagingAndSortingRepository<Company, Long> {
}
----

. Add JPA and REST Repository support to the +io.pivotal.demo.quotes.CompaniesApplication+ class that was generated by Spring Initializr.
+
[source,java]
----
@SpringBootApplication
@EnableJpaRepositories // <---- Add this
@Import(RepositoryRestMvcConfiguration.class) // <---- And this
public class CompaniesApplication {

    public static void main(String[] args) {
        SpringApplication.run(QuotesApplication.class, args);
    }
}
----

. Run the application and open http://localhost:8080/companies in your browser.
+
You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON.
+
So what have you done? Created four small classes and one build file, resulting in a fully-functional REST microservice. The application's +DataSource+ is created automatically by Spring Boot using the in-memory database because no other +DataSource+ was detected in the project.
+
[source,json]
----

{
  "_embedded" : {
    "companies" : [ ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/companies"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/companies"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
----
+
Next we'll import some data.

== Importing Data

. Inside your `'initial` folder, there is a file called `import.sql`. Add it to +src/main/resources+. This is a rather large dataset containing all of the companies and their symbol codes in the NASDAQ and NSYE exchanges. This file will automatically be picked up by Hibernate and imported into the in-memory database.

NOTE: Here we simply use a Spring Boot convention that a file named `import.sql` in the root of the classpath will be executed at startup time. You can read link:http://docs.spring.io/autorepo/docs/spring-boot/current/reference/html/howto-database-initialization.html[here] if you'd like to know more details about it.

. Run the application and access it again in your browser

. Notice the appropriate hypermedia is included for +next+, +previous+, and +self+. You can also select pages and page size by utilizing +?size=n&page=n+ on the URL string. Finally, you can sort the data utilizing +?sort=fieldName+.
+
[source,json]
----

{
  "_embedded" : {
    "companies" : [ {
      "name" : "1347 Capital Corp.",
      "symbol" : "TFSC",
      "exchange" : "NASDAQ",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/companies/1"
        },
        "company" : {
          "href" : "http://localhost:8080/companies/1"
        }
      }

	  ....

    }, {
      "name" : "A V Homes, Inc.",
      "symbol" : "AVHI",
      "exchange" : "NASDAQ",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/companies/20"
        },
        "company" : {
          "href" : "http://localhost:8080/companies/20"
        }
      }
    } ]
  },
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/companies?page=0&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/companies"
    },
    "next" : {
      "href" : "http://localhost:8080/companies?page=1&size=20"
    },
    "last" : {
      "href" : "http://localhost:8080/companies?page=320&size=20"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/companies"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 6419,
    "totalPages" : 321,
    "number" : 0
  }
}
----

. Try to access the following urls to see how the application behaves:
* http://localhost:8080/companies?size=5
* http://localhost:8080/companies?size=5&page=3
* http://localhost:8080/companies?sort=symbol,desc

+
Next we'll add searching capabilities.

== Adding Search

. Let's add some additional finder methods to +CompanyRepository+:
+
[source,java]
----
@RestResource(path = "name", rel = "name")
Page<Company> findByNameIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "nameContains", rel = "nameContains")
Page<Company> findByNameContainsIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "symbol", rel = "symbol")
Page<Company> findBySymbolIgnoreCase(@Param("q") String symbol, Pageable pageable);

@RestResource(path = "exchange", rel = "exchange")
Page<Company> findByExchange(@Param("q") String exchange, Pageable pageable);
----

. Run the application
+

. Access the application again. Notice that hypermedia for a new +search+ endpoint has appeared at the end of the page.
+
[source,bash]
----
{
...
  "_links" : {
    "next" : {
      "href" : "http://localhost:8080/companies?page=1&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/companies{?page,size,sort}",
      "templated" : true
    },
    "search" : {
      "href" : "http://localhost:8080/companies/search"
    }
},
...
----

NOTE: The `search` endpoint is automatically added by `Spring Data REST` when you have declared at least one `findBy` method 

. Access the new +search+ endpoint on http://localhost:8080/companies/search
+
[source,bash]
----
{
  "_links" : {
    "nameContains" : {
      "href" : "http://localhost:8080/companies/search/nameContains{?q,page,size,sort}",
      "templated" : true
    },
    "symbol" : {
      "href" : "http://localhost:8080/companies/search/symbol{?q,page,size,sort}",
      "templated" : true
    },
    "name" : {
      "href" : "http://localhost:8080/companies/search/name{?q,page,size,sort}",
      "templated" : true
    },
    "exchange" : {
      "href" : "http://localhost:8080/companies/search/exchange{?q,page,size,sort}",
      "templated" : true
    },
    "self" : {
      "href" : "http://localhost:8080/companies/search"
    }
  }
}
----
+
Note that we now have new search endpoints for each of the finders that we added.

. Try a few of these endpoints. Feel free to substitute your own values for the parameters.
+
http://localhost:8080/companies/search/exchange?q=NASDAQ
http://localhost:8080/companies/search/name?q=Amerco
http://localhost:8080/companies/search/nameContains?q=Apple&size=5

== Pushing to Cloud Foundry

. An empty `manifest.yml` file has been placed at the root of your project. Paste the below configuration inside your manifest file:
+
[source,yml]
----
---
applications:
- name: companies
  host: companies-${random-word}
  memory: 512M
  instances: 1
  path: target/lab_03a-companies-0.0.1-SNAPSHOT.jar
  timeout: 180 # to give time for the data to import
----

. Build the JAR and push it to Cloud Foundry (you need to leave the IDE to do this):
+
[source,bash]
----
mvn package
cf push
----

. Once it has uploaded and run the buildpack, you should see output like this ...
+
[source,bash]
----

1 of 1 instances running

App started

OK

App companies was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.0_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) && SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.10.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY org.springframework.boot.loader.JarLauncher`

Showing health and status for app companies in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: companies-getable-section.cfapps.pez.pivotal.io
last uploaded: Thu Nov 26 11:02:33 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory           disk           details
#0   running   2015-11-26 07:03:09 PM   0.0%   442.3M of 512M   151.1M of 1G
----

. Access the application at the random route provided by CF - your URL will be different, look in the App Manager console to see what it is:
+
[source,bash]
----
http://companies-<your_path>.cfapps.io/companies
----
