:compat-mode:
= Lab 05a - Build a Quotes services using MongoDB

Estimated time to complete: 30 minutes


[abstract]
--
In this lab we'll begin the first subproject of our complete cloud-native application architecture: _SpringTrader_, which implements the quotes fetching portion of a ``Trading-like'' application.
This microservice will provide the _Quotes Service_, which will allow us to search for companies and symbols in order to make transactions.

We'll be using the http://dev.markitondemand.com[MarketItOnDemad] API, and we'll model its `Quote and Company as a Stock` concept in this microservice.
--


== Exploring springtrader-quotes

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_01/session_05/lab_05a/initial/springtrader-quotes
----
+
and import the project (via `pom.xml`) into your IDE.


. Explore the new `quotes` microservice:
- How many domain classes do you now have?
- How many controller classes?
+
You can see that `html`, `css` and `javascript` files are not included in `springtrader-quotes`. They will all be contained in a `web` microservice (dedicated to the web layer)


. Run the application using an embedded version of MongoDB
. Access the application at http://localhost:8086/quote/msft

+
You should see the below:

[source,json]
----
{
   "Symbol":"MSFT",
   "Name":"Microsoft Corp",
   "Exchange":"NASDAQ",
   "Status":"SUCCESS",
   "LastPrice":53.95,
   "Change":0.260000000000005,
   "ChangePercent":0.484261501210663,
   "Timestamp":"Fri Nov 27 17:59:00 GMTZ 2015",
   "MSDate":42335.5409722222,
   "MarketCap":4.3094790635E11,
   "Volume":716782,
   "ChangeYTD":46.45,
   "ChangePercentYTD":16.1463939720129,
   "High":54.08,
   "Low":53.81,
   "Open":53.94
}
----

== Preparing for Cloud Foundry

. We want to bind to a MongoDB data source when running on Cloud Foundry, so let's create one:
+
----
$ cf cs p-mongodb development springtrader-quotes-db
Creating service springtrader-quotes-db in org cqueiroz-pivot / space development as cqueiroz@pivotal.io...
OK
----

NOTE: if you are using Pivotal Web Service, the above service is not available in the command line. You just need to create it using the Web console at https://console.run.pivotal.io. You can select a MongoDB  service and name it `springtrader-quotes-db`.

. Go into the package `io.pivotal.sprintrader.quotes.config` and observe the differences between `MongoCloudConfig` (`cloud` profile) and `MongoLocalConfig` (`local` profile)
+
As you will see, the `local` profile provides you with a MongoDB in-memory database. The `cloud` profile will rely on the service that you have just created on Cloud Foundry.

. Open `src/main/resources/application.yml` and see that a `cloud` profile has been setup in preparation for deployment to Cloud Foundry:
+
----
...
---
spring:
  profiles: cloud
---
...
----

. Rebuild the JAR:
+
----
$ mvn clean package
----

== Deploying to Cloud Foundry

. Open your `manifest.yml` file and paste inside the following configuration:
+
[source,yml]
----
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_ACTIVE: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: quotes
  random-route: true
  path: target/lab_05a-quotes-1.0.0-SNAPSHOT.jar
  services: [ springtrader-quotes-db ]
----

. Push to Cloud Foundry:
+
----
$ cf push

...

Showing health and status for app quotes in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: quotes-undespising-lenition.cfapps.pez.pivotal.io
last uploaded: Mon Dec 7 22:17:58 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main java-opts open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory           disk           details
#0   running   2015-12-07 07:18:48 PM   3.7%   367.2M of 512M   140.2M of 1G
----

. Access the application at the random route provided by CF (such as `http://quotes-undespising-lenition.cfapps.io/quote/aapl`). The output should look like:
+
[source,json]
----
{
   "Symbol":"AAPL",
   "Name":"Apple Inc.",
   "Exchange":"NASDAQ",
   "Status":"SUCCESS",
   "LastPrice":117.82,
   "Change":-0.210000000000008,
   "ChangePercent":-0.177920867576047,
   "Timestamp":"Fri Nov 27 17:59:00 GMTZ 2015",
   "MSDate":42335.5409722222,
   "MarketCap":6.5688549842E11,
   "Volume":859197,
   "ChangeYTD":110.38,
   "ChangePercentYTD":6.74035151295524,
   "High":118.41,
   "Low":117.6,
   "Open":118.27
}
----
